owner: CIAourense
repo: statusservices

sites:
  - name: Web Concello
    url: https://www.ourense.gal
  - name: Sede electrónica - Concello de Ourense
    url: https://sede.ourense.gob.es

status-website:
  baseUrl: /statusservices
  logoUrl: https://ourense.gal/static/public/img/logoconcello.be4f95277d1d.png
  name: Web Status - Concello de Ourense
  introTitle: "**Web Status** Concello de Ourense"

i18n:
  activeIncidents: Incidentes activos
  allSystemsOperational: Todos los sistemas están operativos
